### ISSUE TITLE
pheno.txt missing newlines (when running epistasis_local.py w/ Covar column)

### ISSUE THREAD

**Issue by ChrisGottsacker** [Parks-Laboratory/epistasis_pipeline#6]
pheno.txt file looks like...

> FID	IID	BF_Percent_Growth_0to8wks129X1.SvJ	1	99.99346365129X1.SvJ	2	100.2235168129X1.SvJ

when it should be...

> FID	IID	MALE_BF_PERCENT_8wks
> 129X1.SvJ	1	24.174
> 129X1.SvJ	2	37.95

NOTE: as far as I can tell, this bug does not appear when the "Covar" column is absent from the input file.

**Comment by tzrtzr000** [comment]
I commented out line 116 on epistasis_local.py because I remember before that Brain once generated pheno.txt with double spaced. Chris do you want me to update them or just leave as it is?

**Comment by tzrtzr000** [comment]
I just ran the script again using BF_PERCENT_GROWTH_0to2wks_MALE.txt and here is the result that I got... 

> FID	IID	BF_Percent_Growth_0to2wks
> 129X1.SvJ	0	23.92454966
> 129X1.SvJ	1	44.31946308
> 129X1.SvJ	2	45.00972278
> 129X1.SvJ	3	75.29252972
> 129X1.SvJ	4	86.11750396
> 129X1.SvJ	5	89.53160757
> ... 

the result is in my folder: E:\TZR\EpistasisBF_PERCENT_GROWTH_0to2wks_MALE.pheno.txt and I am actually confused why it would cause the problem... 
 the correct output for pheno.txt. I used python 3.5.2 although I do not think that is the reason...

**Comment by ChrisGottsacker** [comment]
Run *epistasis_local.py* with [BF_PERCENT_GROWTH_0to8_M_F.txt](https://github.com/Parks-Laboratory/epistasis_pipeline/files/1011835/BF_PERCENT_GROWTH_0to8_M_F.txt), and you'll see what I mean.

*BF_PERCENT_GROWTH_0to2wks_MALE.txt* does not contain a "Covar" column, so the issue will not occur.

**Comment by tzrtzr000** [comment]
I fixed both problems and uploaded the _epistasis_local.py_ to Github. Thanks for the feedback Chris!

**Comment by ChrisGottsacker** [comment]
I took the liberty of removing a couple exit() calls that were ending the script prematurely, and commented out the code that prints the input file.
